before_script:
- set GRADLE_USER_HOME=`pwd`/.gradle
- cd ./ks-api
 
build:
  script:
    - ./gradlew assemble
  only:
    - master
 
test:
  stage: test
  script:
    - ./gradlew test
  only:
    - master
    
after_script:
  - echo "End CI"
