before_script:
- set GRADLE_USER_HOME=C:\Users\krist\OneDrive - Office 365 Fontys\Semester 3\its\gradle-6.6.1
- ./gradlew
 
build:
  script:
    - ./gradlew assemble
 
test:
  stage: test
  script:
    - ./gradlew test
 
after_script:
  - echo "End CI"
