before_script:
- set GRADLE_USER_HOME=`pwd`/.gradle
- ./ks-api/gradlew
 
build:
  script:
    - ./ks-api/gradlew assemble
 
test:
  stage: test
  script:
    - ./ks-api/gradlew test
 
after_script:
  - echo "End CI"
