stages:
  - build
  - test
  - sonarqube
  - deploy

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  dependencies:
    - build
  script:
    - ./gradlew test

sonarqube:
  stage: sonarqube
  dependencies:
    - test
  script:
    - ./gradlew sonarqube

deploy:
  stage: deploy
  dependencies:
    - test
  before_script:
    - ./gradlew assemble
  script:
    - docker build -t ks-app:latest .
    - docker run --name ks-app-container --rm -dp 8080:8080 ks-app
  only:
    - master

after_script:
  - echo "End CI"
