before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew
 
build:
  script:
    - ./gradlew assemble
 
test:
  stage: test
  script:
    - ./gradlew test
 
after_script:
  - echo "End CI"
