before_script:
- set GRADLE_USER_HOME=`pwd`/.gradle
- ./ks-api/gradlew
 
build:
  script:
    - ./ks-api/gradlew assemble
  only:
    - master
 
test:
  stage: test
  script:
    - ./ks-api/gradlew test
  only:
    - master
    
after_script:
  - echo "End CI"
