before_script:
- set GRADLE_USER_HOME=`pwd`/.gradle
- ./gradlew
 
build:
  script:
    - ./gradlew
  only:
    - master
 
test:
  stage: test
  script:
    - ./gradlew
  only:
    - master
    
after_script:
  - echo "End CI"
