before_script:
- ./gradlew
 
build:
  script:
    - ./gradlew assemble
  only:
    - master
 
test:
  stage: test
  script:
    - ./gradlew test
  only:
    - master
    
after_script:
  - echo "End CI"
