#before_script:
#- set GRADLE_USER_HOME=`pwd`/.gradle
#- ./gradlew
stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew assemble
 
test:
  stage: test
  dependencies:
    - build
  script:
    - ./gradlew test
    
after_script:
  - echo "End CI"
