stages:
  - build
  - test
  - sonarqube

build:
  stage: build
  script:
    - cd ./ks-api
    - ./gradlew assemble
 
test:
  stage: test
  dependencies:
    - build
  script:
    - cd ./ks-api
    - ./gradlew test

sonarqube:
  stage: sonarqube
  dependencies:
    - test
  script:
    - cd ./ks-api
    - ./gradlew sonarqube
    
after_script:
  - echo "End CI"
